// apps/solidjs/src/App.tsx
import {ChevronDown, ChevronRight, File, Folder} from "lucide-solid";
import {createSignal} from "solid-js";
import {For, Show} from "solid-js/web";
import{cn,nodesData,type Node} from "@recursion-ui/lib"



function App() {
	let [selectedFile, setSelectedFile] = createSignal<string | null>(null);
	return (
		<main>
			<div class="flex">
				<For each={nodesData}>
					{(n) => (
						<Node
							node={n}
							selectFile={(file: string) => setSelectedFile(file)}
						/>
					)}
				</For>
				<div>
					<Show when={selectedFile()}>
						<h2 class="text-xl font-bold">Selected file:</h2>
						<p>{selectedFile()}</p>
					</Show>
				</div>
			</div>
		</main>
	);
}

function Node({
	node,
	selectFile,
}: {node: Node; selectFile: (file: string) => void}) {
	let [isOpen, setIsOpen] = createSignal(false);
	let hasNodes = node.nodes.length > 0;
	return (
		<>
			<button
				type="button"
				class={cn("flex items-center gap-1 my-2", hasNodes ? "ml-2" : "ml-5")}
				onClick={() => {
					if (hasNodes) {
						setIsOpen(!isOpen());
					} else {
						selectFile(node.name);
					}
				}}
			>
				<Show when={hasNodes}>
					<Show when={isOpen()} fallback={<ChevronRight />}>
						<ChevronDown />
					</Show>
				</Show>
				<Show when={hasNodes} fallback={<File />}>
					<Folder />
				</Show>
				<span>{node.name}</span>
			</button>
			<Show when={isOpen()}>
				<ul class="pl-4">
					<For each={node.nodes}>
						{(n) => (
							<li>
								<Node node={n} selectFile={selectFile} />
							</li>
						)}
					</For>
				</ul>
			</Show>
		</>
	);
}

export default App;

// apps/react/src/App.tsx
import {ChevronRight, File, Folder, FolderOpen} from "lucide-react";
import "./App.css";
import {useCallback, useState} from "react";
import{cn,nodesData,type Node} from "@recursion-ui/lib"



function App() {
	let [selectedFile, setSelectedFile] = useState<Node | null>(null);
	const selectFile = useCallback((file: Node): void => {
		setSelectedFile(file);
	}, []);

	return (
		<main>
			<div className="flex max-w-[900px] justify-between">
				<div>
					{nodesData.map((n) => (
						<Node key={n.name} node={n} selectFile={selectFile} />
					))}
				</div>
				<div>
					{selectedFile ? (
						<div>
							<h2>
								<span className="font-semibold">{selectedFile.name}</span> has
								been selected
							</h2>
						</div>
					) : (
						<p>Select a file</p>
					)}
				</div>
			</div>
		</main>
	);
}

function Node({
	node,
	selectFile,
}: {node: Node; selectFile: (file: Node) => void}) {
	let [open, setOpen] = useState(false);
	let hasChildNodes = node.nodes.length > 0;
	return (
		<>
			<button
				className={cn(
					"flex items-center gap-1",
					hasChildNodes ? "mb-3" : "ml-1",
				)}
				type="button"
				onClick={() => {
					if (hasChildNodes) {
						setOpen((p) => !p);
					} else {
						selectFile(node);
					}
				}}
				key={node.name}
			>
				<>
					{hasChildNodes && (
						<ChevronRight size={20} className={open ? "rotate-90" : ""} />
					)}
					{hasChildNodes ? (
						open ? (
							<FolderOpen size={20} />
						) : (
							<Folder size={20} />
						)
					) : (
						<File size={20} />
					)}
					<span>{node.name}</span>
				</>
			</button>
			{open && (
				<div className="mb-3 ml-5">
					{node.nodes.map((n) => (
						<Node key={n.name} node={n} selectFile={selectFile} />
					))}
				</div>
			)}
		</>
	);
}

export default App;
